FROM golang:1.22.1-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
COPY ./certs/service-key.json ./certs/service-key.json
RUN go mod download

CMD ["air", "-c", ".air.toml"]