FROM golang:1.22.5-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
COPY ./certs/zitadel-key.json ./certs/zitadel-key.json
RUN go mod download

CMD ["air", "-c", ".air.toml"]