name: test-service

on:
  push:
    branches:
      - main
    paths:
      - service/**
      - .github/workflows/test-service.yml
  pull_request:
    branches:
      - main
    paths:
      - service/**
      - .github/workflows/test-service.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./service
        run: go test ./... -cover
