name: test-frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        working-directory: ./frontend
        run: npm install
      - name: Run tests
        working-directory: ./frontend
        run: npm run test
